name: CI-Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          .cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install dependencies
      run: npm ci

    - name: Run Unit Tests
      run: npm run test:unit -- --coverage --watchAll=false

    - name: Run Integration Tests
      run: npm run test:integration -- --watchAll=false

    - name: Run Component Tests
      run: npm run test:component -- --watchAll=false

    # Add coverage reporting
    - name: Upload Coverage Report
      uses: actions/upload-pages-artifact@v3
      with:
        name: coverage-report
        path: coverage/

    - name: Lint and Static Analysis
      run: npm run lint